// <auto-generated />
using System;
using FMA.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FMA.API.Migrations
{
    [DbContext(typeof(FmaContext))]
    [Migration("20190801161845_changeToEntities")]
    partial class changeToEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FMA.API.Entities.Affiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Affiliations");
                });

            modelBuilder.Entity("FMA.API.Entities.Capital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Capitals");

                    b.HasData(
                        new { Id = new Guid("4c793930-8632-48ad-9850-499f74de0853"), Description = "Central City is the official capital and also the seat of government in Amestris. The National Central Library, Central Command, the 5 National Laboratories, and Amestris' Parliament are all located in Central. Aside from its symbol as a military headquarters, Central is also a bustling metropolis and arguably Amestris' largest city, complete with nearly everything Amestrian society has to offer as well as a lasting and rarely disturbed sense of peace created by its proximity to the government's imposing presence. After the events in the eastern regions of Amestris and the Elrics' excursion to the southern region, much of the Fullmetal Alchemist story takes place in Central, as it also serves as the Homunculi's home base, the heart of which is located deep beneath Central Command Headquarters", Name = "Central City" }
                    );
                });

            modelBuilder.Entity("FMA.API.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abilities");

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("Goal");

                    b.Property<string>("LastName");

                    b.Property<Guid>("NationalityId");

                    b.Property<Guid>("OccupationId");

                    b.Property<string>("Rank");

                    b.Property<string>("Weapon");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.HasIndex("OccupationId");

                    b.ToTable("Characters");

                    b.HasData(
                        new { Id = new Guid("b8be8110-3841-4064-b0a5-b8987bf8c3b2"), Abilities = "Flame-Based Alchemy", Age = 29, FirstName = "Roy", Goal = "Becoming Fuhrer", LastName = "Mustang", NationalityId = new Guid("900f6350-82c5-4e5d-aff3-1b74adf3612d"), OccupationId = new Guid("99216871-834b-4108-9bfc-86e7bc1f5a50"), Rank = "Lieutenant Colonel", Weapon = "Ignition Cloth Gloves" }
                    );
                });

            modelBuilder.Entity("FMA.API.Entities.CharacterAffiliation", b =>
                {
                    b.Property<Guid>("MemberId");

                    b.Property<Guid>("AffiliationId");

                    b.HasKey("MemberId", "AffiliationId");

                    b.HasIndex("AffiliationId");

                    b.ToTable("CharacterAffiliation");
                });

            modelBuilder.Entity("FMA.API.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CapitalId");

                    b.Property<Guid>("CurrencyId");

                    b.Property<int>("Founded");

                    b.Property<string>("Government");

                    b.Property<Guid>("GovernorId");

                    b.Property<string>("Name");

                    b.Property<Guid>("NationalityId");

                    b.Property<int>("Population");

                    b.HasKey("Id");

                    b.HasIndex("CapitalId")
                        .IsUnique();

                    b.HasIndex("CurrencyId")
                        .IsUnique();

                    b.HasIndex("GovernorId")
                        .IsUnique();

                    b.HasIndex("NationalityId")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new { Id = new Guid("63891193-dce2-41ee-bdb0-6cfaf69b6d27"), CapitalId = new Guid("4c793930-8632-48ad-9850-499f74de0853"), CurrencyId = new Guid("f268e74c-1840-4835-ae3e-47e6915099ae"), Founded = 0, GovernorId = new Guid("00000000-0000-0000-0000-000000000000"), Name = "Amestris", NationalityId = new Guid("900f6350-82c5-4e5d-aff3-1b74adf3612d"), Population = 50000000 }
                    );
                });

            modelBuilder.Entity("FMA.API.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new { Id = new Guid("f268e74c-1840-4835-ae3e-47e6915099ae"), Description = "The Cens is the standard unit of currency in Amestris and is available in both paper bills and varied metal coins. It can be inferred that the paper bills are worth more, similar to many real-life currencies. It is equal to about one Japanese Yen in the real world.", Name = "Cenz" }
                    );
                });

            modelBuilder.Entity("FMA.API.Entities.Nationality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new { Id = new Guid("900f6350-82c5-4e5d-aff3-1b74adf3612d"), Name = "Amestrian" }
                    );
                });

            modelBuilder.Entity("FMA.API.Entities.Occupation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Decsription");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Occupations");

                    b.HasData(
                        new { Id = new Guid("99216871-834b-4108-9bfc-86e7bc1f5a50"), Decsription = "A State Alchemist is an alchemist employed by the Amestrian State Military as part of an elite government mandated program.", Name = "State Alchemist" }
                    );
                });

            modelBuilder.Entity("FMA.API.Entities.Character", b =>
                {
                    b.HasOne("FMA.API.Entities.Nationality", "Nationality")
                        .WithMany("Members")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FMA.API.Entities.Occupation", "Occupation")
                        .WithMany("Members")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FMA.API.Entities.CharacterAffiliation", b =>
                {
                    b.HasOne("FMA.API.Entities.Affiliation", "Affiliation")
                        .WithMany("KnownMembers")
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FMA.API.Entities.Character", "Member")
                        .WithMany("Affiliations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FMA.API.Entities.Country", b =>
                {
                    b.HasOne("FMA.API.Entities.Capital", "Capital")
                        .WithOne("Country")
                        .HasForeignKey("FMA.API.Entities.Country", "CapitalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FMA.API.Entities.Currency", "Currency")
                        .WithOne("Country")
                        .HasForeignKey("FMA.API.Entities.Country", "CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FMA.API.Entities.Character", "Governor")
                        .WithOne("Country")
                        .HasForeignKey("FMA.API.Entities.Country", "GovernorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FMA.API.Entities.Nationality", "Nationality")
                        .WithOne("Country")
                        .HasForeignKey("FMA.API.Entities.Country", "NationalityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
